name: Deploy Streamlit App

on:
  push:
    branches:
      - web-app  # replace with your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit script
      run: |
        export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
        streamlit run app.py